version: '2'
services:
    waterless-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/waterless/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=waterless
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
